FROM mysql:8.0.28-oracle

# Configuration for the MySQL database.
ADD ./etc/mysql/conf.d/mysql.cnf /etc/mysql/conf.d/mysql.cnf

# Initialization scripts (should be mounted as a docker compose volume).
# /docker-entrypoint-initdb.d/
