name: "appbigsexypoems"

services:

  # CFML server.
  # http://app.local.bigsexypoems.com
  #
  # Administrator / CFIDE:
  # - Url: http://app.local.bigsexypoems.com:8080/CFIDE/administrator/index.cfm
  # - Password: commandbox
  cfml:
    build:
      context: "./cfml/"
      dockerfile: "docker/Dockerfile"
    ports:
      - "80:8080"
      - "443:8443" # SSL certificate provided via server.json
      - "8080:8080"
    volumes:
      - "./cfml/app:/app"
    healthcheck:
      test: "echo hello"
    depends_on:
      mysql:
        condition: service_healthy
      mail:
        condition: service_healthy

  # MySQL server.
  # http://app.local.bigsexypoems.com:3306/
  mysql:
    build:
      context: "./mysql/docker/"
      dockerfile: "Dockerfile"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "bigsexypoems"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      # Initialization scripts, to be executed in alphabetical order.
      - "./cfml/app/db:/docker-entrypoint-initdb.d"
      # Allow docker to manage the data persistence folder (MySQL doesn't work when you
      # mount the data on the host machine).
      - "mysql_data:/var/lib/mysql"
    healthcheck:
      test: "echo hello"

  # SMTP server.
  # http://app.local.bigsexypoems.com:8025/
  mail:
    build:
      context: "./mail/docker/"
      dockerfile: "Dockerfile"
    ports:
      - "8025:8025"
    healthcheck:
      test: "echo hello"

volumes:
  mysql_data:
