<cfoutput>

	<!doctype html>
	<html lang="en">
	<head>
		<cfmodule template="/client/_shared/tag/meta.cfm" />
		<cfmodule template="/client/_shared/tag/title.cfm" />
		<cfmodule template="/client/_shared/tag/favicon.cfm" />
		<!--- These "HTML" files are dynamically generated by the Parcel build. --->
		<cfinclude template="/wwwroot/static/main/vendor/vendor.html">
		<cfinclude template="/wwwroot/static/main/dev/dev.html">
	</head>
	<body xk7wfn class="body">

		<cfmodule template="/client/_shared/tag/svgSprite.cfm" />
		<cfmodule template="/client/_shared/tag/flashMessage.cfm" />

		#request.response.body#

		<cfmodule template="/client/_shared/tag/localDevelopment.cfm" />

	</body>
	</html>

</cfoutput>
