<cfoutput>

	<!doctype html>
	<html lang="en" #ui.attrTheme()#>
	<head>
		<cfmodule template="/client/_shared/tag/meta.cfm" />
		<cfmodule template="/client/_shared/tag/title.cfm" />
		<cfmodule template="/client/_shared/tag/favicon.cfm" />
		<!--- These CFML modules are dynamically generated by the Parcel build. --->
		<cfmodule template="/wwwroot/static/main/vendor/vendor.cfm" />
		<cfmodule template="/wwwroot/static/main/dev/dev.cfm" />
	</head>
	<body xk7wfn class="body">

		<cfmodule template="/client/_shared/tag/svgSprite.cfm" />
		<cfmodule template="/client/_shared/tag/flashMessage.cfm" />

		#request.response.body#

		<cfmodule template="/client/_shared/tag/localDevelopment.cfm" />

	</body>
	</html>

</cfoutput>
