<cfoutput>

	<!doctype html>
	<html lang="en">
	<head>
		<cfmodule template="/client/_shared/tag/meta.cfm" />
		<cfmodule template="/client/_shared/tag/title.cfm" />
		<cfmodule template="/client/_shared/tag/favicon.cfm" />
		<cfmodule template="/client/_shared/tag/bugsnag.cfm" />
		<!--- These CFML modules are dynamically generated by the Parcel build. --->
		<cfmodule template="/wwwroot/static/main/vendor/vendor.cfm" />
		<cfmodule template="/wwwroot/static/main/go/go.cfm" />
	</head>
	<body x-data zj98do class="zj98do">

		<main zj98do class="content">
			#request.response.body#
		</main>

		<cfmodule template="/client/_shared/tag/localDevelopment.cfm" />

	</body>
	</html>

</cfoutput>
