<cfoutput>

	<!doctype html>
	<html lang="en" #ui.attrTheme()#>
	<head>
		<cfmodule template="/client/_shared/tag/meta.cfm" />
		<cfmodule template="/client/_shared/tag/title.cfm" />
		<cfmodule template="/client/_shared/tag/favicon.cfm" />
		<cfmodule template="/client/_shared/tag/bugsnag.cfm" />
		<!--- These CFML modules are dynamically generated by the Parcel build. --->
		<cfmodule template="/wwwroot/static/main/vendor/vendor.cfm" />
		<cfmodule template="/wwwroot/static/main/auth/auth.cfm" />
	</head>
	<body x-data l9uznd class="body">

		<cfmodule template="/client/_shared/tag/svgSprite.cfm" />
		<cfmodule template="/client/_shared/tag/flashMessage.cfm" />

		<main l9uznd class="main">
			#request.response.body#
		</main>

		<cfmodule template="/client/_shared/tag/toaster.cfm" />
		<cfmodule template="/client/_shared/tag/localDevelopment.cfm" />

	</body>
	</html>

</cfoutput>
